- name: outlineplaybook
  hosts: webserver
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: date/time stamp for when the playbook start
     command: /usr/bin/date
     register: timestamp_start
   - debug: var=timestamp_start
   - name: install the apache server
     action: yum=httpd state=latest
     notify: restart httpd server
   - name: verify that the web server is running
     command: systemctl status httpd
     register: result
   - debug: var=result
   - name: install client software telnet
     action: yum=telnet state=latest
   - name: install client software lynx
     action: yum=lynx state=latest
   - name: log all the packages install on the system
     command: yum list installed
     register: yum_install_list
   - debug: var=yum_install_list
   - name: date/time stamp for when the playbook ends
     command: /usr/bin/date
     register: timestamp_end
   - debug: var=timestamp_end
  handlers:
   - name: restart httpd server
     service: name=httpd state=restarted