- name: My First Playbook
  hosts: webserver
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
   Playbook_version: 0.1b
  vars_files:
   - conf/copyright.yml
   - conf/webdefaults.yml
  vars_prompt:
   - name: web_domain
     prompt: Web Domain
  tasks:
    - name: Install Apche Web Server
      action: yum name=httpd state=installed
      async: 300
      poll: 3
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
