- name: LOOKUP PLAYBOOK EXAMPLE
  hosts: webserver
  user: ansible
  sudo: ssh
  connection: ssh
  gather_facts: no
  tasks:
   - debug: msg="Lookup the SuperHero for BRUCE {{ lookup('csvfile','Bruce file=lookup.csv delimiter=, default=NOMATCH') }}"