- name: outlineplaybook
  hosts: webserver
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: date/time stamp for when the playbook start
     raw: /usr/bin/date > /home/ansible/playbook_start.log
   - name: install the apache server
     action: yum=httpd state=latest
   - name: start the web server
     service: name=httpd state=restarted
   - name: verify that the web server is running
     command: systemctl status httpd
     register: result
   - debug: var=result
   - name: install client software telnet
     action: yum=telnet state=latest
   - name: install client software lynx
     action: yum=lynx state=latest
   - name: log all the packages install on the system
     raw: yum list installed > /home/ansible/install_list.log
   - name: date/time stamp for when the playbook ends
     raw: /usr/bin/date > /home/ansible/playbook_end.log